# Generated by Django 5.2.3 on 2025-07-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_desc', models.CharField(max_length=600)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_image', models.URLField()),
            ],
        ),
    ]
